[package]
name = "bevy-macroquad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.12.1", default-features = false }
kdl = "4.6.0"
macroquad = "0.4.4"
